Improvements
Serializator/octopus-giggles pull request #1
Opened 2021-07-20 19:59 UTC by ThEWiZ76

2021-07-22 11:59 UTC, Serializator requested changes
Please use a label instead of `MAINTAINER` as it is deprecated ❤️ 
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

2021-07-22 11:59 UTC, Serializator commented on Dockerfile
> +MAINTAINER "Serializator"
Use of `MAINTAINER` is deprecated, please use a label for this as well.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

2021-07-22 20:05 UTC, ThEWiZ76 commented on Dockerfile
> +MAINTAINER "Serializator"
updated the PR with the requested improvements

2021-09-05 21:16 UTC, ThEWiZ76 commented on Dockerfile
> +MAINTAINER "Serializator"
@Serializator did you have a look?

2023-10-09 06:35 UTC, closed without merging